baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menu.main]]
  name = "A propos"
  url = "/a-propos"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.social]]
name = "GitHub"
url = "https://github.com/VotreCompteGithub"
pre = "<i class='fab fa-github'></i>"


[[menu.social]]
name = "LinkedIn"
url = "https://linkedin.com/VotreCompteTwitter"
pre = "<i class='fab fa-linkedin'></i>"


[[menu.footer]]
name = "A propos"
url = "/about"

[[menu.footer]]
name = "Protection des données"
url = "/protection-des-donnees"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
    author = "Arthur Pendragon"
    authorImage = "/images/avatar.jpg"