baseURL: http://example.org/
languageCode: en-us
title: Julien Creach

theme: "toha"

languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: French
    weight: 2

enableEmoji: true

params:
  background: "images/background.jpg"
  enableBlogPost: true
  newsletter:
    enable: false
  darkMode:
    enable: true
    provider: darkreader
    default: system
    